### ISSUE TITLE
Error cannot resolve module `fs`

### ISSUE THREAD

**Issue by samb90** [dailymotion/vast-client-js#156]
Keep seeing the error `Error cannot resolve module 'fs'` when trying to import `vast-client-js` as follows `var vast = require('vast-client');`.

**Comment by michaelvial** [comment]
Well spotted, the [URL handler for Node](https://github.com/dailymotion/vast-client-js/blob/master/src/urlhandlers/node.coffee) requires `fs`, `http` and `url` packages, but theses are not defined in `package.json`.

Definitely a bug.

**Comment by samb90** [comment]
We are trying to run this on the client in a chromium browser.

Does this library require NodeJs?

**Comment by michaelvial** [comment]
No, you can use it on a browser. But when you're loading the lib with`require`, the NodeJs URLhandler is included. And it needs `fs`, `http` and `url` packages to run, even if you will never use it browser-side.

In the meantime, you can use the bundle file `vast-client.js`. This should work

**Comment by chrishoage** [comment]
This happens in webpack.

**Comment by dharFr** [comment]
In `package.json`, the [`"main"`](https://github.com/dailymotion/vast-client-js/blob/6d1826fd1a274457ab86a90344eb677f1d0bf52b/package.json#L27) field should probably head to `"vast-client.js"` (bundled version) instead of `"dist/index.js"` (root module). 

I'm not sure about the proper way to handle this in `pacakge.json`. I feel like both paths should be provided in the `package.json` so anyone can choose which version to use, but definitely, it should default to `"vast-client.js"`. 

In the meantime, you can use one of the following methods to work around the problem : 
 - require the bundled version directly: `var vast = require('vast-client/vast-client.js')`
 - or, if you want to keep bundling the modules, prevent webpack from parsing the node module  using [`module.noParse`](https://webpack.js.org/configuration/module/#module-noparse) option in webpack config :  
``` js
module: {
  noParse: [
    /vast-client\/dist\/urlhandlers\/node\.js/,
  ],
},
```

**Comment by dharFr** [comment]
According to [webpack documentation](https://webpack.js.org/guides/author-libraries/#final-steps), the proper way in probably something like : 
``` json
{
    "main": "vast-client.js",
    "module": "dist/index.js"
}```
I'll give it a try and send a PR.
