### ISSUE TITLE
The options.response property is no longer available

### ISSUE THREAD

**Issue by Grafluxe** [dailymotion/vast-client-js#240]
Hello, 
In `v1.x.x` of your codebase, we were able to create inline wrapper tags as such:
```js
const options = {
  response: createVastWrapperAd(vastUrl, adParameters)
};

vastClient.get(null, options, callback);
```
As of `v2.0.0`, how can this be done?

Thanks

**Comment by eliamaino-fp** [comment]
Hi @Grafluxe, in the `v2.0.0` we tried to differentiate a little bit more the behaviour of `VASTClient` and `VASTParser`, in order to have a clearer usage of the two.

As `1.x` documentation says about the parameter : 
"`String` response – A VAST XML document. When response is provided, no Ajax request is made and thus the url parameter is ignored."

You should now use the `parseVAST` method provided by the `VASTParser` which accepts an XML document and returns a `Promise` which resolves in a `VASTResponse`.

See: https://github.com/dailymotion/vast-client-js/blob/master/docs/api/vast-parser.md#parsevastvastxml-options

So your code should look more or less like this:
```javascript
import { VASTParser } from 'vast-client'

const vastParser = new VASTParser();
const wrapperAd = createVastWrapperAd(vastUrl, adParameters); // This should be a VAST XML

vastParser.parseVAST(wrapperAd, options)
  .then(vastResponse => {
    // Use the parsed VAST
  });
```

I hope this is what you are looking for :)

**Comment by Grafluxe** [comment]
Works as expected. Thanks for the quick response and clear details on how to migrate.

**Comment by eliamaino-fp** [comment]
Perfect, I'll close the issue then :)
