### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by alexpashkov** [dailymotion/vast-client-js#242]
Hello, there are TypeScript definitions for 1.7 version, will definitions for 2.x be available in the nearest future?

**Comment by eliamaino-fp** [comment]
Hi @alexpashkov, if you refer to this https://www.npmjs.com/package/@types/vast-client, the definitions were not directly provided by maintainers of the library.

Currently we don't have plans to provide updated definitions in the nearest future (since at dailymotion we don't use typescript, this is not directly a priority for us 😃).

If you want to update the definitions for the `2.x` version of the library you're more than welcome (and I can help you in case)

**Comment by kobawan** [comment]
Hi @alexpashkov, I created a PR with types for vast-client version 2.1. You can review it here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31726

**Comment by eliamaino-fp** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31726 got merged. I'll close the issue
