### ISSUE TITLE
Can it be used in React Native?

### ISSUE THREAD

**Issue by samtoya** [dailymotion/vast-client-js#305]

**Comment by kobawan** [comment]
Hi! I haven't tried it but I don't see a reason why it couldn't. The codebase is framework agnostic :)

**Comment by samtoya** [comment]
I was having issues with internal libraries used like *http*.

![Screenshot 2019-09-09 at 9 22 19 AM](https://user-images.githubusercontent.com/20547136/64519278-5eb77000-d2e3-11e9-8559-c9632d6e0b71.png)

I've tried following the steps provided, but still unable to get it working, please any help regarding this would be greatly appreciated.

Thanks.

**Comment by jakub-g** [comment]
@samtoya I don't know much about react native either but let me explain.

`vast-client-js` is a module compatible both with the browsers and nodejs.
This is achieved due to some build time magic [here](https://github.com/dailymotion/vast-client-js/blob/master/src/url_handler.js#L2) and [here](https://github.com/dailymotion/vast-client-js/blob/master/rollup.config.js#L65-L67) and [`package.json` config](https://github.com/dailymotion/vast-client-js/blob/master/package.json#L25-L29)
The lines above tell about different entry points. 

It seems that react native takes the `main` entrypoint, so it gets served the code destined for nodejs. React native is kind of like nodejs, but it doesn't have certain  nodejs builtin modules. It does have `fetch` and `XMLHttpRequest` though apparently. So it's a hybrid between browser and nodejs in fact.

Due to lack of `http` module it fails at this line of code, from your screenshot:
https://github.com/dailymotion/vast-client-js/blob/master/src/urlhandlers/node_url_handler.js#L3

Feel free to work on adding react native compatibility if you want. 
But make sure it doesn't break the existing functionality nor increase the bundle size for the browser.

Some relevant links:
https://stackoverflow.com/questions/29371694/react-native-and-requirehttp
https://facebook.github.io/react-native/docs/network#using-other-networking-libraries
https://github.com/facebook/react-native/issues/375
https://github.com/parshap/node-libs-react-native
https://github.com/tradle/react-native-http

**Comment by ZacharieTFR** [comment]
Hello, I’m closing this issue because it has been inactive for a year. 

Please reopen if you still encounter this issue with the latest version: https://github.com/dailymotion/vast-client-js/releases/ 😉 

Thank you!
