### ISSUE TITLE
Math.round on Quartile Tracking?

### ISSUE THREAD

**Issue by shaqq** [dailymotion/vast-client-js#31]
I was just curious about the usage Math.round when calculating the quartiles, here:

https://github.com/dailymotion/vast-client-js/blob/master/src/tracker.coffee#L27

The value ends up being a floating point number anyway, because it's dividing by 100. Should we take out the Math.round bit?

**Comment by rs** [comment]
Introduced here: https://github.com/dailymotion/vast-client-js/commit/9ad865c99aae0806320621a9f688c758328e351d

What do you think @dharFr?

**Comment by dharFr** [comment]
Not sure to remember why I ended up with this...
I guess it's most likely a mistyped version of `Math.round(25 * @assetDuration / 100)`, which would not be much useful because we finally use the resulting value as a boundary (see [here](https://github.com/dailymotion/vast-client-js/commit/9ad865c99aae0806320621a9f688c758328e351d#diff-3575e111f8719c68619c1bbdce3e53feR63)).

Even if it's a minor issue, we probably want to fix the typo for consistency. While we're at it, I think we could also remove the `Math.round()` and it won't break anything.
