### ISSUE TITLE
firstQuartile and thirdQuartile network calls not executing

### ISSUE THREAD

**Issue by ghuserchris** [dailymotion/vast-client-js#449]
I am not seeing the network calls for "firstQuartile" and "thirdQuartile", even though I am seeing them for "start" and "midpoint". Example network call for "midpoint" is 

`https://servedbyadbutler.com/vast-callback.spark?adID=10082&productID=175725&publisherID=67570&placementID=89964&zoneID=6484&campaignID=18166&scheduleID=88539&type=midpoint&linearID=10071&creativeID=10071`

When I check for those events in vastTracker.on("firstQuartile", () => ...), those are firing, so I don't know why the network calls are not.

The ad is a 31 second video.

**Comment by Rapha0511** [comment]
Hello !

Which version of vast-client are you using ?

Do you have a sample of code or a codepen to provide us, as well as the VAST document you are using, so that we can help you more precisely ?

Here is an exemple of the usage of the VASTTracker that might be helpfull  :

https://codepen.io/Raphael-LEVIN/pen/xxQwoxP

**Comment by ghuserchris** [comment]
Thank you for the quick response, the root cause was the vast response had the tracking events named as "first-quartile" and "third_quartile" instead of "firstQuartile" and thirdQuartile" ...
